# Copyright (C) 2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

VENDOR_PATH := vendor/huawei/HwCamera2

PRODUCT_COPY_FILES += \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/CN_pic_1.png:system/cameraplugins/mode/documentrecognition/CN_pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/CN_pic_1_dm.png:system/cameraplugins/mode/documentrecognition/CN_pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/CN_pic_2.png:system/cameraplugins/mode/documentrecognition/CN_pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/CN_pic_2_dm.png:system/cameraplugins/mode/documentrecognition/CN_pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/documentrecognition.png:system/cameraplugins/mode/documentrecognition/documentrecognition.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/documentrecognition_dark.png:system/cameraplugins/mode/documentrecognition/documentrecognition_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/documentrecognition_dm.png:system/cameraplugins/mode/documentrecognition/documentrecognition_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/CN_documents_01.png:system/cameraplugins/mode/documentrecognition/emui9/CN_documents_01.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/CN_documents_01_dm.png:system/cameraplugins/mode/documentrecognition/emui9/CN_documents_01_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/CN_documents_02.png:system/cameraplugins/mode/documentrecognition/emui9/CN_documents_02.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/CN_documents_02_dm.png:system/cameraplugins/mode/documentrecognition/emui9/CN_documents_02_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/documents_01.png:system/cameraplugins/mode/documentrecognition/emui9/documents_01.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/documents_01_dm.png:system/cameraplugins/mode/documentrecognition/emui9/documents_01_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/documents_02.png:system/cameraplugins/mode/documentrecognition/emui9/documents_02.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/documents_02_dm.png:system/cameraplugins/mode/documentrecognition/emui9/documents_02_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/ic_camera_documents.png:system/cameraplugins/mode/documentrecognition/emui9/ic_camera_documents.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/ic_camera_documents_dm.png:system/cameraplugins/mode/documentrecognition/emui9/ic_camera_documents_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/emui9/ic_documents_dark.png:system/cameraplugins/mode/documentrecognition/emui9/ic_documents_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/pic_1.png:system/cameraplugins/mode/documentrecognition/pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/pic_1_dm.png:system/cameraplugins/mode/documentrecognition/pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/pic_2.png:system/cameraplugins/mode/documentrecognition/pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/documentrecognition/pic_2_dm.png:system/cameraplugins/mode/documentrecognition/pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/CN_pic_1.png:system/cameraplugins/mode/food/CN_pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/CN_pic_1_dm.png:system/cameraplugins/mode/food/CN_pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/CN_pic_2.png:system/cameraplugins/mode/food/CN_pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/CN_pic_2_dm.png:system/cameraplugins/mode/food/CN_pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/CN_food_01.png:system/cameraplugins/mode/food/emui9/CN_food_01.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/CN_food_01_dm.png:system/cameraplugins/mode/food/emui9/CN_food_01_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/CN_food_02.png:system/cameraplugins/mode/food/emui9/CN_food_02.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/CN_food_02_dm.png:system/cameraplugins/mode/food/emui9/CN_food_02_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/food_01.png:system/cameraplugins/mode/food/emui9/food_01.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/food_01_dm.png:system/cameraplugins/mode/food/emui9/food_01_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/food_02.png:system/cameraplugins/mode/food/emui9/food_02.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/food_02_dm.png:system/cameraplugins/mode/food/emui9/food_02_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/ic_camera_food.png:system/cameraplugins/mode/food/emui9/ic_camera_food.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/ic_camera_food_dm.png:system/cameraplugins/mode/food/emui9/ic_camera_food_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/emui9/ic_food_dark.png:system/cameraplugins/mode/food/emui9/ic_food_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/food.png:system/cameraplugins/mode/food/food.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/food_dark.png:system/cameraplugins/mode/food/food_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/food_dm.png:system/cameraplugins/mode/food/food_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/pic_1.png:system/cameraplugins/mode/food/pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/pic_1_dm.png:system/cameraplugins/mode/food/pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/pic_2.png:system/cameraplugins/mode/food/pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/food/pic_2_dm.png:system/cameraplugins/mode/food/pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/CN_pic_1.png:system/cameraplugins/mode/makeup/CN_pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/CN_pic_1_dm.png:system/cameraplugins/mode/makeup/CN_pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/CN_pic_2.png:system/cameraplugins/mode/makeup/CN_pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/CN_pic_2_dm.png:system/cameraplugins/mode/makeup/CN_pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/makeup.png:system/cameraplugins/mode/makeup/makeup.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/makeup_dark.png:system/cameraplugins/mode/makeup/makeup_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/makeup_dm.png:system/cameraplugins/mode/makeup/makeup_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/pic_1.png:system/cameraplugins/mode/makeup/pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/pic_1_dm.png:system/cameraplugins/mode/makeup/pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/pic_2.png:system/cameraplugins/mode/makeup/pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/makeup/pic_2_dm.png:system/cameraplugins/mode/makeup/pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/CN_pic_1.png:system/cameraplugins/mode/objectrecognition/CN_pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/CN_pic_1_dm.png:system/cameraplugins/mode/objectrecognition/CN_pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/CN_pic_2.png:system/cameraplugins/mode/objectrecognition/CN_pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/CN_pic_2_dm.png:system/cameraplugins/mode/objectrecognition/CN_pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/CN_search_01.png:system/cameraplugins/mode/objectrecognition/emui9.0/CN_search_01.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/CN_search_01_dm.png:system/cameraplugins/mode/objectrecognition/emui9.0/CN_search_01_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/CN_search_02.png:system/cameraplugins/mode/objectrecognition/emui9.0/CN_search_02.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/CN_search_02_dm.png:system/cameraplugins/mode/objectrecognition/emui9.0/CN_search_02_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/ic_camera_search.png:system/cameraplugins/mode/objectrecognition/emui9.0/ic_camera_search.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/ic_camera_search_dm.png:system/cameraplugins/mode/objectrecognition/emui9.0/ic_camera_search_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/ic_search_dark.png:system/cameraplugins/mode/objectrecognition/emui9.0/ic_search_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/search_01.png:system/cameraplugins/mode/objectrecognition/emui9.0/search_01.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/search_01_dm.png:system/cameraplugins/mode/objectrecognition/emui9.0/search_01_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/search_02.png:system/cameraplugins/mode/objectrecognition/emui9.0/search_02.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/emui9.0/search_02_dm.png:system/cameraplugins/mode/objectrecognition/emui9.0/search_02_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/object_recognition.png:system/cameraplugins/mode/objectrecognition/object_recognition.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/object_recognition_dark.png:system/cameraplugins/mode/objectrecognition/object_recognition_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/object_recognition_dm.png:system/cameraplugins/mode/objectrecognition/object_recognition_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/pic_1.png:system/cameraplugins/mode/objectrecognition/pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/pic_1_dm.png:system/cameraplugins/mode/objectrecognition/pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/pic_2.png:system/cameraplugins/mode/objectrecognition/pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/objectrecognition/pic_2_dm.png:system/cameraplugins/mode/objectrecognition/pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/CN_pic_1.png:system/cameraplugins/mode/voicephoto/CN_pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/CN_pic_1_dm.png:system/cameraplugins/mode/voicephoto/CN_pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/CN_pic_2.png:system/cameraplugins/mode/voicephoto/CN_pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/CN_pic_2_dm.png:system/cameraplugins/mode/voicephoto/CN_pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/pic_1.png:system/cameraplugins/mode/voicephoto/pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/pic_1_dm.png:system/cameraplugins/mode/voicephoto/pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/pic_2.png:system/cameraplugins/mode/voicephoto/pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/pic_2_dm.png:system/cameraplugins/mode/voicephoto/pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/voicephoto.png:system/cameraplugins/mode/voicephoto/voicephoto.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/voicephoto_dark.png:system/cameraplugins/mode/voicephoto/voicephoto_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/voicephoto/voicephoto_dm.png:system/cameraplugins/mode/voicephoto/voicephoto_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/CN_pic_1.png:system/cameraplugins/mode/watermark/CN_pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/CN_pic_1_dm.png:system/cameraplugins/mode/watermark/CN_pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/CN_pic_2.png:system/cameraplugins/mode/watermark/CN_pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/CN_pic_2_dm.png:system/cameraplugins/mode/watermark/CN_pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/CN_watermark_01.png:system/cameraplugins/mode/watermark/emui9/CN_watermark_01.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/CN_watermark_01_dm.png:system/cameraplugins/mode/watermark/emui9/CN_watermark_01_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/CN_watermark_02.png:system/cameraplugins/mode/watermark/emui9/CN_watermark_02.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/CN_watermark_02_dm.png:system/cameraplugins/mode/watermark/emui9/CN_watermark_02_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/ic_camera_watermark.png:system/cameraplugins/mode/watermark/emui9/ic_camera_watermark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/ic_camera_watermark_dm.png:system/cameraplugins/mode/watermark/emui9/ic_camera_watermark_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/ic_watermark_dark.png:system/cameraplugins/mode/watermark/emui9/ic_watermark_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/watermark_01.png:system/cameraplugins/mode/watermark/emui9/watermark_01.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/watermark_01_dm.png:system/cameraplugins/mode/watermark/emui9/watermark_01_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/watermark_02.png:system/cameraplugins/mode/watermark/emui9/watermark_02.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/emui9/watermark_02_dm.png:system/cameraplugins/mode/watermark/emui9/watermark_02_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/pic_1.png:system/cameraplugins/mode/watermark/pic_1.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/pic_1_dm.png:system/cameraplugins/mode/watermark/pic_1_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/pic_2.png:system/cameraplugins/mode/watermark/pic_2.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/pic_2_dm.png:system/cameraplugins/mode/watermark/pic_2_dm.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/watermark.png:system/cameraplugins/mode/watermark/watermark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/watermark_dark.png:system/cameraplugins/mode/watermark/watermark_dark.png \
    $(VENDOR_PATH)/system/cameraplugins/mode/watermark/watermark_dm.png:system/cameraplugins/mode/watermark/watermark_dm.png \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libHW_Pano_f.so:system/priv-app/HwCamera2/lib/arm/libHW_Pano_f.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libHwPostCamera_jni.so:system/priv-app/HwCamera2/lib/arm/libHwPostCamera_jni.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libIvw35.so:system/priv-app/HwCamera2/lib/arm/libIvw35.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libJniVoiceCapture.so:system/priv-app/HwCamera2/lib/arm/libJniVoiceCapture.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libTargetTracking.so:system/priv-app/HwCamera2/lib/arm/libTargetTracking.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libfyusenet.so:system/priv-app/HwCamera2/lib/arm/libfyusenet.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libgif_maker.so:system/priv-app/HwCamera2/lib/arm/libgif_maker.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libjni_front_panorama_beauty_hidl.so:system/priv-app/HwCamera2/lib/arm/libjni_front_panorama_beauty_hidl.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libjni_front_panorama_camera2.so:system/priv-app/HwCamera2/lib/arm/libjni_front_panorama_camera2.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libjni_mrc_cg_filters_camera2.so:system/priv-app/HwCamera2/lib/arm/libjni_mrc_cg_filters_camera2.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libmorpho_memory_allocator.so:system/priv-app/HwCamera2/lib/arm/libmorpho_memory_allocator.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libmorpho_panorama_gp.so:system/priv-app/HwCamera2/lib/arm/libmorpho_panorama_gp.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libscanner.so:system/priv-app/HwCamera2/lib/arm/libscanner.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/libtrack.so:system/priv-app/HwCamera2/lib/arm/libtrack.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/vendor.huawei.hardware.camera.cfgsvr@1.0.so:system/priv-app/HwCamera2/lib/arm/vendor.huawei.hardware.camera.cfgsvr@1.0.so \
    $(VENDOR_PATH)/system/priv-app/HwCamera2/lib/arm/vendor.huawei.hardware.camera.cfgsvr@1.1.so:system/priv-app/HwCamera2/lib/arm/vendor.huawei.hardware.camera.cfgsvr@1.1.so \
    $(VENDOR_PATH)/system/watermark/wm/wm_1_1.zip:system/watermark/wm/wm_1_1.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_1_2.zip:system/watermark/wm/wm_1_2.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_1_3.zip:system/watermark/wm/wm_1_3.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_1_4.zip:system/watermark/wm/wm_1_4.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_1_5.zip:system/watermark/wm/wm_1_5.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_1_6.zip:system/watermark/wm/wm_1_6.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_1_7.zip:system/watermark/wm/wm_1_7.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_1.zip:system/watermark/wm/wm_2_1.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_10.zip:system/watermark/wm/wm_2_10.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_11.zip:system/watermark/wm/wm_2_11.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_12.zip:system/watermark/wm/wm_2_12.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_13.zip:system/watermark/wm/wm_2_13.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_14.zip:system/watermark/wm/wm_2_14.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_15.zip:system/watermark/wm/wm_2_15.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_2.zip:system/watermark/wm/wm_2_2.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_3.zip:system/watermark/wm/wm_2_3.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_4.zip:system/watermark/wm/wm_2_4.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_5.zip:system/watermark/wm/wm_2_5.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_6.zip:system/watermark/wm/wm_2_6.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_7.zip:system/watermark/wm/wm_2_7.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_8.zip:system/watermark/wm/wm_2_8.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_2_9.zip:system/watermark/wm/wm_2_9.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_1.zip:system/watermark/wm/wm_3_1.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_10.zip:system/watermark/wm/wm_3_10.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_2.zip:system/watermark/wm/wm_3_2.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_3.zip:system/watermark/wm/wm_3_3.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_4.zip:system/watermark/wm/wm_3_4.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_5.zip:system/watermark/wm/wm_3_5.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_6.zip:system/watermark/wm/wm_3_6.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_8.zip:system/watermark/wm/wm_3_8.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_3_9.zip:system/watermark/wm/wm_3_9.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_5_1.zip:system/watermark/wm/wm_5_1.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_5_2.zip:system/watermark/wm/wm_5_2.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_5_3.zip:system/watermark/wm/wm_5_3.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_5_4.zip:system/watermark/wm/wm_5_4.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_5_5.zip:system/watermark/wm/wm_5_5.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_5_6.zip:system/watermark/wm/wm_5_6.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_5_7.zip:system/watermark/wm/wm_5_7.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_1.zip:system/watermark/wm/wm_6_1.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_10.zip:system/watermark/wm/wm_6_10.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_11.zip:system/watermark/wm/wm_6_11.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_12.zip:system/watermark/wm/wm_6_12.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_13.zip:system/watermark/wm/wm_6_13.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_14.zip:system/watermark/wm/wm_6_14.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_2.zip:system/watermark/wm/wm_6_2.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_3.zip:system/watermark/wm/wm_6_3.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_4.zip:system/watermark/wm/wm_6_4.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_7.zip:system/watermark/wm/wm_6_7.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_8.zip:system/watermark/wm/wm_6_8.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_6_9.zip:system/watermark/wm/wm_6_9.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_7_1.zip:system/watermark/wm/wm_7_1.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_7_2.zip:system/watermark/wm/wm_7_2.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_7_3.zip:system/watermark/wm/wm_7_3.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_7_4.zip:system/watermark/wm/wm_7_4.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_7_5.zip:system/watermark/wm/wm_7_5.zip \
    $(VENDOR_PATH)/system/watermark/wm/wm_7_6.zip:system/watermark/wm/wm_7_6.zip \

PRODUCT_PACKAGES += \
    HwCamera2
